// Every endpoint the frontend calls must exist in the backend's OpenAPI
// description (openapi.json, generated by the backend's `npm run openapi`).
// When the backend renames or removes one, this fails here instead of in a
// member's browser.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { test } from 'node:test';
import { API, ENTITY_RESOURCES } from './endpoints.js';

const spec = JSON.parse(fs.readFileSync(new URL('./openapi.json', import.meta.url), 'utf8'));

// A concrete path (families/abc) matches the spec's template (families/{id}).
const matches = (template, path) => new RegExp(`^${template.replace(/\{[^}]+\}/g, '[^/]+')}$`).test(path);
const has = (method, url) => {
  const path = url.split('?')[0];
  return Object.entries(spec.paths).some(([template, operations]) => matches(template, path) && operations[method.toLowerCase()]);
};

// The calls base44Client.js makes, by method.
const CALLS = [
  ['POST', API.uploads],
  ['POST', API.auth.registrations],
  ['POST', API.auth.otpVerifications],
  ['POST', API.auth.otps],
  ['POST', API.auth.sessions],
  ['DELETE', API.auth.currentSession],
  ['POST', API.auth.passwordResets],
  ['POST', API.auth.passwordResetConfirmations],
  ['PUT', API.auth.password],
  ['GET', API.auth.me],
  ['PATCH', API.auth.me],
  ['POST', API.auth.invitations],
  ['GET', API.me.family],
  ['GET', API.me.feedback],
  ['GET', API.familyVerification('NPSI-FAM-000001')],
  ['GET', API.applicationStatus('NPSI-APP-2026-000001', '9876543210')],
  ['GET', API.mobileAvailability('9876543210')],
  ['GET', API.emailAvailability('a@b.c')],
  ['GET', API.stats],
];
const REVIEWED = ['Application', 'StudentApplication', 'TransferRequest'];
const BATCH = ['FamilyMember', 'Notification'];
for (const entity of Object.keys(ENTITY_RESOURCES)) {
  CALLS.push(['GET', API.entities.collection(entity)], ['POST', API.entities.collection(entity)]);
  CALLS.push(['PATCH', API.entities.item(entity, 'id-1')], ['DELETE', API.entities.item(entity, 'id-1')]);
  if (REVIEWED.includes(entity)) CALLS.push(['POST', API.entities.review(entity, 'id-1')]);
  if (BATCH.includes(entity)) CALLS.push(['POST', API.entities.batch(entity)]);
}

test('every endpoint the frontend calls exists in the backend API', () => {
  const missing = CALLS.filter(([method, url]) => !has(method, url)).map(([method, url]) => `${method} ${url}`);
  assert.deepEqual(missing, []);
});

test('the spec is the backend API (sanity check)', () => {
  assert.equal(spec.info.title, 'NPS Indore portal API');
  assert.ok(Object.keys(spec.paths).length > 40);
});
